name: 'Setup Node.js and install npm dependencies'
description: 'Configure Node.js and install npm dependencies while managing all aspects of caching.'
inputs:
    node-version:
        description: 'Optional. The Node.js version to use. When not specified, the version specified in .nvmrc will be used.'
        required: false
        type: string

runs:
    using: 'composite'
    steps:
        - name: Use desired version of Node.js
          uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
          with:
              node-version-file: '.nvmrc'
              node-version: ${{ inputs.node-version }}
              check-latest: true
              cache: npm

        - name: Get Node.js and npm version
          id: node-version
          run: |
              echo "NODE_VERSION=$(node -v)" >> "$GITHUB_OUTPUT"
          shell: bash

        - name: Cache node_modules
          id: cache-node_modules
          uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
          with:
              path: '**/node_modules'
              key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ steps.node-version.outputs.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

        - name: Install npm dependencies
          if: ${{ steps.cache-node_modules.outputs.cache-hit != 'true' }}
          run: |
              npm ci
          shell: bash
        - name: Upload npm logs as an artifact on failure
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
          if: failure()
          with:
              name: npm-logs
              path: C:\npm\cache\_logs

        # On cache hit, we run the post-install script to match the native `npm ci` behavior.
        # An example of this is to patch `node_modules` using patch-package.
        - name: Post-install
          if: ${{ steps.cache-node_modules.outputs.cache-hit == 'true' }}
          run: |
              # Run the post-install script for the root project.
              npm run postinstall
              # Run the post-install scripts for workspaces.
              npx lerna run postinstall
          shell: bash
