on:
    pull_request_target:
        types: [opened]
    push:
name: Pull request automation

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    pull-request-automation:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
            pull-requests: write
        if: ${{ github.repository == 'WordPress/gutenberg' }}

        steps:
            # Checkout defaults to using the branch which triggered the event, which
            # isn't necessarily `trunk` (e.g. in the case of a merge).
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: trunk
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - uses: ./packages/project-management-automation
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
