name: Storybook build and Smoke Tests

on: pull_request

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    check:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}
        timeout-minutes: 30

        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Build Storybook
              run: npm run storybook:build

            # - name: Install Playwright dependencies
            #   run: npx playwright install --with-deps

            # - name: Serve Storybook and run tests
            #   run: |
            #       npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            #       "npx http-server ./storybook/build --port 50240 --silent" \
            #       "npx wait-on tcp:127.0.0.1:50240 && \
            #       NODE_PATH=./node_modules \
            #       npx --package=@storybook/test-runner -- \
            #       test-storybook --url http://localhost:50240 --config-dir ./storybook"
